services:
  - type: web
    name: emmanuel-selicour-portfolio
    runtime: static
    buildCommand: ""
    staticPublishPath: ./portfolio
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    domains:
      - emmanuel-selicour.online

  - type: web
    name: es-company-webservices
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    domains:
      - webservices.emmanuel-selicour.online
